# Generated by Django 2.2.7 on 2019-12-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('product_options', models.CharField(choices=[('account', 'ACCOUNT'), ('checking', 'CHECKING'), ('balance', 'BALANCE')], default=('account', 'ACCOUNT'), max_length=9)),
            ],
        ),
    ]
