# Generated by Django 2.2.7 on 2019-12-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
                ('branch_location', models.CharField(max_length=200)),
            ],
        ),
    ]
